r/aws_ebs_volume_attachment: new list resource
Add list resource support for the `aws_ebs_volume_attachment` resource.

```console
% make t K=ec2 T='TestAccEC2EBS(?:EBS)?VolumeAttachment_List' ACCTEST_PARALLELISM=5
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-ebs_volume-list 🌿...
TF_ACC=1 go1.26.2 test ./internal/service/ec2/... -v -count 1 -parallel 5 -run='TestAccEC2EBS(?:EBS)?VolumeAttachment_List'  -timeout 360m -vet=off
2026/04/21 13:38:31 Creating Terraform AWS Provider (SDKv2-style)...
2026/04/21 13:38:31 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccEC2EBSVolumeAttachment_List_includeResource (87.98s)
--- PASS: TestAccEC2EBSVolumeAttachment_List_basic (98.66s)
--- PASS: TestAccEC2EBSVolumeAttachment_List_regionOverride (114.69s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        121.917s
```

```console
% make t K=ec2 T='TestAccEC2EBS(?:EBS)?VolumeAttachment_' ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-ebs_volume-list 🌿...
TF_ACC=1 go1.26.2 test ./internal/service/ec2/... -v -count 1 -parallel 4 -run='TestAccEC2EBS(?:EBS)?VolumeAttachment_'  -timeout 360m -vet=off
2026/04/21 14:01:20 Creating Terraform AWS Provider (SDKv2-style)...
2026/04/21 14:01:20 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccEC2EBSVolumeAttachment_List_basic (83.21s)
=== CONT  TestAccEC2EBSVolumeAttachment_List_regionOverride
--- PASS: TestAccEC2EBSVolumeAttachment_basic (91.66s)
=== CONT  TestAccEC2EBSVolumeAttachment_List_includeResource
--- PASS: TestAccEC2EBSEBSVolumeAttachment_Identity_basic (107.25s)
=== CONT  TestAccEC2EBSEBSVolumeAttachment_Identity_ExistingResource_noRefreshNoChange
--- PASS: TestAccEC2EBSEBSVolumeAttachment_Identity_ExistingResource_basic (138.41s)
=== CONT  TestAccEC2EBSVolumeAttachment_update
--- PASS: TestAccEC2EBSVolumeAttachment_List_includeResource (97.07s)
=== CONT  TestAccEC2EBSVolumeAttachment_stopInstance
--- PASS: TestAccEC2EBSVolumeAttachment_List_regionOverride (115.41s)
=== CONT  TestAccEC2EBSVolumeAttachment_disappears
--- PASS: TestAccEC2EBSEBSVolumeAttachment_Identity_ExistingResource_noRefreshNoChange (112.84s)
=== CONT  TestAccEC2EBSVolumeAttachment_attachStopped
--- PASS: TestAccEC2EBSVolumeAttachment_update (111.46s)
=== CONT  TestAccEC2EBSVolumeAttachment_skipDestroy
--- PASS: TestAccEC2EBSVolumeAttachment_disappears (86.20s)
=== CONT  TestAccEC2EBSEBSVolumeAttachment_Identity_regionOverride
--- PASS: TestAccEC2EBSVolumeAttachment_skipDestroy (76.66s)
--- PASS: TestAccEC2EBSVolumeAttachment_attachStopped (139.20s)
--- PASS: TestAccEC2EBSEBSVolumeAttachment_Identity_regionOverride (107.88s)
=== NAME  TestAccEC2EBSVolumeAttachment_stopInstance
    ebs_volume_attachment_test.go:208: Error running post-test destroy, there may be dangling resources: exit status 1

        Error: waiting for EBS Volume (vol-0ba2c6bbc158a6956) delete: timeout while waiting for resource to be gone (last state: 'deleting', timeout: 10m0s): operation error EC2: DescribeVolumes, context deadline exceeded

--- FAIL: TestAccEC2EBSVolumeAttachment_stopInstance (689.28s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        885.386s
```

Failure is transient (due to slow internal cleanup operations on the AWS
side) and resolves on subsequent runs.