r/aws_ec2_secondary_subnet(test): add `_List_regionOverride` test
NOTE: secondary networks are currently only allow-listed in the
`us-east-2` region of our primary testing account. As such, the region
override test will be skipped due to the `UnsupportedOperation` error
returned during test setup.

```console
% make t K=ec2 T=TestAccEC2SecondarySubnet_List_region
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-ec2_secondary_network-list 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2SecondarySubnet_List_region'  -timeout 360m -vet=off
2026/02/19 15:44:21 Creating Terraform AWS Provider (SDKv2-style)...
2026/02/19 15:44:21 Initializing Terraform AWS Provider (SDKv2-style)...

=== CONT  TestAccEC2SecondarySubnet_List_regionOverride
    acctest.go:1787: skipping test for aws/us-east-2: Error running apply: exit status 1

        Error: creating EC2 Secondary Network

          with aws_ec2_secondary_network.test,
          on main.tf line 14, in resource "aws_ec2_secondary_network" "test":
          14: resource "aws_ec2_secondary_network" "test" {

        operation error EC2: CreateSecondaryNetwork, https response error StatusCode:
        400, RequestID: e42d8faf-0554-4890-b7d4-e8a2129f23b1, api error
        UnsupportedOperation: The functionality you requested is not available in
        this region.
--- SKIP: TestAccEC2SecondarySubnet_List_regionOverride (5.72s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        12.765s
```