r/aws_ec2_secondary_network(test): add `_List_regionOverride`
NOTE: secondary networks are currently only allow-listed in the
`us-east-2` region of our primary testing account. As such, the region
override test will be skipped due to the `UnsupportedOperation` error
returned during test setup.

```console
% make t K=ec2 T=TestAccEC2SecondaryNetwork_List_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-ec2_secondary_network-list 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2SecondaryNetwork_List_'  -timeout 360m -vet=off
2026/02/19 10:55:29 Creating Terraform AWS Provider (SDKv2-style)...
2026/02/19 10:55:29 Initializing Terraform AWS Provider (SDKv2-style)...

=== NAME  TestAccEC2SecondaryNetwork_List_regionOverride
    acctest.go:1787: skipping test for aws/us-east-2: Error running apply: exit status 1

        Error: creating EC2 Secondary Network

          with aws_ec2_secondary_network.test[1],
          on main.tf line 4, in resource "aws_ec2_secondary_network" "test":
           4: resource "aws_ec2_secondary_network" "test" {

        operation error EC2: CreateSecondaryNetwork, https response error StatusCode:
        400, RequestID: d849dd8d-dc93-48aa-bb9a-6ba5761ef097, api error
        UnsupportedOperation: The functionality you requested is not available in
        this region.

        Error: creating EC2 Secondary Network

          with aws_ec2_secondary_network.test[0],
          on main.tf line 4, in resource "aws_ec2_secondary_network" "test":
           4: resource "aws_ec2_secondary_network" "test" {

        operation error EC2: CreateSecondaryNetwork, https response error StatusCode:
        400, RequestID: dbeeb494-d936-4700-ad65-8a9e90884093, api error
        UnsupportedOperation: The functionality you requested is not available in
        this region.
--- SKIP: TestAccEC2SecondaryNetwork_List_regionOverride (4.25s)
--- PASS: TestAccEC2SecondaryNetwork_List_basic (24.81s)
--- PASS: TestAccEC2SecondaryNetwork_List_includeResource (25.03s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        32.092s
```