feat: support `go-vcr` in name generation
This change passes the randomness seed generated during VCR-enabled acceptance testing through to the CRUD handlers via context. The CRUD handlers can then pass along the context to the various name-generation functions within `internal/create` to ensure provider-generated names remain deterministic when VCR is enabled.

Some notes about the implementation:

- The randomness source is passed from acceptance test setup via `provider.Meta`.
  - A new getter and setter are added to the `conns.AWSClient` struct to facilitate storing and retrieving the source as necessary.
  - The "bootstrap" context interceptor functions for both Plugin SDK V2 and Plugin Framework provider instances handle transferring the randomness source from `provider.Meta` into the CRUD execution context.
  - This is necessary because values stored in context during test initialization are not persisted through to the context send during CRUD execution.
- As both `create.Name` and the underlying `Generate` method on the `nameGenerator` accept context - deterministic name generation will function for both the basic name generator and instances where a custom generator is set up for a single resource.

Before:

```console
% VCR_MODE=REPLAY_ONLY VCR_PATH=/Users/jaredbaker/development/_vcr-testdata/ make t K=logs T=TestAccLogsLogGroup_nameGenerate
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 main 🌿...
TF_ACC=1 go1.25.6 test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsLogGroup_nameGenerate'  -timeout 360m -vet=off
2026/02/02 11:32:19 Creating Terraform AWS Provider (SDKv2-style)...
2026/02/02 11:32:19 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLogsLogGroup_nameGenerate
=== PAUSE TestAccLogsLogGroup_nameGenerate
=== CONT  TestAccLogsLogGroup_nameGenerate
    group_test.go:67: Step 1/2 error: Error running apply: exit status 1

        Error: creating CloudWatch Logs Log Group (terraform-20260202163223003500000001): operation error CloudWatch Logs: CreateLogGroup, https response error StatusCode: 0, RequestID: , request send failed, Post "https://logs.us-west-2.amazonaws.com/": requested interaction not found

          with aws_cloudwatch_log_group.test,
          on terraform_plugin_test.tf line 12, in resource "aws_cloudwatch_log_group" "test":
          12: resource "aws_cloudwatch_log_group" "test" {}

    panic.go:615: randomness source not found for test TestAccLogsLogGroup_nameGenerate
--- FAIL: TestAccLogsLogGroup_nameGenerate (3.69s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/logs       10.567s
```

After:

```console
% VCR_MODE=REPLAY_ONLY VCR_PATH=/Users/jaredbaker/development/_vcr-testdata/ make t K=logs T=TestAccLogsLogGroup_nameGenerate
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-create-name-ctx 🌿...
TF_ACC=1 go1.25.6 test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsLogGroup_nameGenerate'  -timeout 360m -vet=off
2026/02/02 11:32:26 Creating Terraform AWS Provider (SDKv2-style)...
2026/02/02 11:32:26 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLogsLogGroup_nameGenerate
=== PAUSE TestAccLogsLogGroup_nameGenerate
=== CONT  TestAccLogsLogGroup_nameGenerate
    group_test.go:67: stopping VCR recorder
    group_test.go:67: persisting randomness seed
--- PASS: TestAccLogsLogGroup_nameGenerate (10.25s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/logs       16.998s
```

Full replayed acceptance tests:

```console
% VCR_MODE=REPLAY_ONLY VCR_PATH=/Users/jaredbaker/development/_vcr-testdata/ make t K=logs T=TestAccLogsLogGroup_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-create-name-ctx 🌿...
TF_ACC=1 go1.25.6 test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsLogGroup_'  -timeout 360m -vet=off
2026/02/02 11:06:59 Creating Terraform AWS Provider (SDKv2-style)...
2026/02/02 11:07:00 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLogsLogGroup_Identity_Basic
=== PAUSE TestAccLogsLogGroup_Identity_Basic
=== RUN   TestAccLogsLogGroup_Identity_RegionOverride
=== PAUSE TestAccLogsLogGroup_Identity_RegionOverride
=== RUN   TestAccLogsLogGroup_Identity_ExistingResource
    group_identity_gen_test.go:208: no cassette found on disk for TestAccLogsLogGroup_Identity_ExistingResource, please replay this testcase in RECORD_ONLY mode - open /Users/jaredbaker/development/_vcr-testdata/TestAccLogsLogGroup_Identity_ExistingResource.seed: no such file or directory
--- FAIL: TestAccLogsLogGroup_Identity_ExistingResource (0.00s)
=== RUN   TestAccLogsLogGroup_Identity_ExistingResource_NoRefresh_NoChange
    group_identity_gen_test.go:266: no cassette found on disk for TestAccLogsLogGroup_Identity_ExistingResource_NoRefresh_NoChange, please replay this testcase in RECORD_ONLY mode - open /Users/jaredbaker/development/_vcr-testdata/TestAccLogsLogGroup_Identity_ExistingResource_NoRefresh_NoChange.seed: no such file or directory
--- FAIL: TestAccLogsLogGroup_Identity_ExistingResource_NoRefresh_NoChange (0.00s)
=== RUN   TestAccLogsLogGroup_List_Basic
    group_list_test.go:30: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_List_Basic (0.00s)
=== RUN   TestAccLogsLogGroup_List_RegionOverride
    group_list_test.go:92: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_List_RegionOverride (0.00s)
=== RUN   TestAccLogsLogGroup_tags
=== PAUSE TestAccLogsLogGroup_tags
=== RUN   TestAccLogsLogGroup_tags_null
=== PAUSE TestAccLogsLogGroup_tags_null
=== RUN   TestAccLogsLogGroup_tags_EmptyMap
=== PAUSE TestAccLogsLogGroup_tags_EmptyMap
=== RUN   TestAccLogsLogGroup_tags_AddOnUpdate
=== PAUSE TestAccLogsLogGroup_tags_AddOnUpdate
=== RUN   TestAccLogsLogGroup_tags_EmptyTag_OnCreate
=== PAUSE TestAccLogsLogGroup_tags_EmptyTag_OnCreate
=== RUN   TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Add
=== RUN   TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Replace
=== PAUSE TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Replace
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_providerOnly
    group_tags_gen_test.go:766: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_providerOnly (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_nonOverlapping
    group_tags_gen_test.go:951: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_nonOverlapping (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_overlapping
    group_tags_gen_test.go:1115: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_overlapping (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_updateToProviderOnly
    group_tags_gen_test.go:1295: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_updateToProviderOnly (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_updateToResourceOnly
    group_tags_gen_test.go:1389: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_updateToResourceOnly (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_emptyResourceTag
    group_tags_gen_test.go:1482: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_emptyResourceTag (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_emptyProviderOnlyTag
    group_tags_gen_test.go:1551: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_emptyProviderOnlyTag (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_nullOverlappingResourceTag
    group_tags_gen_test.go:1612: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_nullOverlappingResourceTag (0.00s)
=== RUN   TestAccLogsLogGroup_tags_DefaultTags_nullNonOverlappingResourceTag
    group_tags_gen_test.go:1678: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_DefaultTags_nullNonOverlappingResourceTag (0.00s)
=== RUN   TestAccLogsLogGroup_tags_ComputedTag_OnCreate
    group_tags_gen_test.go:1744: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_ComputedTag_OnCreate (0.00s)
=== RUN   TestAccLogsLogGroup_tags_ComputedTag_OnUpdate_Add
    group_tags_gen_test.go:1803: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_ComputedTag_OnUpdate_Add (0.00s)
=== RUN   TestAccLogsLogGroup_tags_ComputedTag_OnUpdate_Replace
    group_tags_gen_test.go:1904: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_ComputedTag_OnUpdate_Replace (0.00s)
=== RUN   TestAccLogsLogGroup_tags_IgnoreTags_Overlap_DefaultTag
    group_tags_gen_test.go:1995: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_IgnoreTags_Overlap_DefaultTag (0.00s)
=== RUN   TestAccLogsLogGroup_tags_IgnoreTags_Overlap_ResourceTag
    group_tags_gen_test.go:2161: go-vcr is not currently supported for test step ProtoV5ProviderFactories
--- SKIP: TestAccLogsLogGroup_tags_IgnoreTags_Overlap_ResourceTag (0.00s)
=== RUN   TestAccLogsLogGroup_basic
=== PAUSE TestAccLogsLogGroup_basic
=== RUN   TestAccLogsLogGroup_nameGenerate
=== PAUSE TestAccLogsLogGroup_nameGenerate
=== RUN   TestAccLogsLogGroup_namePrefix
=== PAUSE TestAccLogsLogGroup_namePrefix
=== RUN   TestAccLogsLogGroup_disappears
=== PAUSE TestAccLogsLogGroup_disappears
=== RUN   TestAccLogsLogGroup_kmsKey
=== PAUSE TestAccLogsLogGroup_kmsKey
=== RUN   TestAccLogsLogGroup_logGroupClass
=== PAUSE TestAccLogsLogGroup_logGroupClass
=== RUN   TestAccLogsLogGroup_retentionPolicy
=== PAUSE TestAccLogsLogGroup_retentionPolicy
=== RUN   TestAccLogsLogGroup_multiple
=== PAUSE TestAccLogsLogGroup_multiple
=== RUN   TestAccLogsLogGroup_skipDestroy
=== PAUSE TestAccLogsLogGroup_skipDestroy
=== RUN   TestAccLogsLogGroup_skipDestroyInconsistentPlan
=== PAUSE TestAccLogsLogGroup_skipDestroyInconsistentPlan
=== RUN   TestAccLogsLogGroup_logGroupClassDELIVERY1
=== PAUSE TestAccLogsLogGroup_logGroupClassDELIVERY1
=== RUN   TestAccLogsLogGroup_logGroupClassDELIVERY2
=== PAUSE TestAccLogsLogGroup_logGroupClassDELIVERY2
=== RUN   TestAccLogsLogGroup_requiredTags
    group_test.go:403: skipping test; environment variable TF_ACC_REQUIRED_TAG_KEY must be set
--- SKIP: TestAccLogsLogGroup_requiredTags (0.00s)
=== RUN   TestAccLogsLogGroup_requiredTags_defaultTags
    group_test.go:494: skipping test; environment variable TF_ACC_REQUIRED_TAG_KEY must be set
--- SKIP: TestAccLogsLogGroup_requiredTags_defaultTags (0.00s)
=== RUN   TestAccLogsLogGroup_requiredTags_warning
    group_test.go:577: skipping test; environment variable TF_ACC_REQUIRED_TAG_KEY must be set
--- SKIP: TestAccLogsLogGroup_requiredTags_warning (0.00s)
=== RUN   TestAccLogsLogGroup_requiredTags_disabled
    group_test.go:675: skipping test; environment variable TF_ACC_REQUIRED_TAG_KEY must be set
--- SKIP: TestAccLogsLogGroup_requiredTags_disabled (0.00s)
=== RUN   TestAccLogsLogGroup_deletionProtectionEnabled
=== PAUSE TestAccLogsLogGroup_deletionProtectionEnabled
=== RUN   TestAccLogsLogGroup_providerMeta
=== PAUSE TestAccLogsLogGroup_providerMeta
=== CONT  TestAccLogsLogGroup_Identity_Basic
=== CONT  TestAccLogsLogGroup_disappears
=== CONT  TestAccLogsLogGroup_tags_EmptyTag_OnCreate
=== CONT  TestAccLogsLogGroup_namePrefix
=== CONT  TestAccLogsLogGroup_nameGenerate
=== CONT  TestAccLogsLogGroup_retentionPolicy
=== CONT  TestAccLogsLogGroup_skipDestroy
=== CONT  TestAccLogsLogGroup_multiple
=== CONT  TestAccLogsLogGroup_kmsKey
=== CONT  TestAccLogsLogGroup_tags_null
=== CONT  TestAccLogsLogGroup_logGroupClass
=== CONT  TestAccLogsLogGroup_tags_EmptyMap
=== CONT  TestAccLogsLogGroup_skipDestroyInconsistentPlan
=== CONT  TestAccLogsLogGroup_providerMeta
=== CONT  TestAccLogsLogGroup_deletionProtectionEnabled
=== CONT  TestAccLogsLogGroup_logGroupClassDELIVERY2
=== CONT  TestAccLogsLogGroup_logGroupClassDELIVERY1
=== CONT  TestAccLogsLogGroup_basic
=== CONT  TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Replace
=== CONT  TestAccLogsLogGroup_tags_AddOnUpdate
=== NAME  TestAccLogsLogGroup_skipDestroy
    group_test.go:287: stopping VCR recorder
    group_test.go:287: persisting randomness seed
--- PASS: TestAccLogsLogGroup_skipDestroy (35.37s)
=== CONT  TestAccLogsLogGroup_tags
=== NAME  TestAccLogsLogGroup_logGroupClass
    group_test.go:192: stopping VCR recorder
    group_test.go:192: persisting randomness seed
--- PASS: TestAccLogsLogGroup_logGroupClass (35.53s)
=== CONT  TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Add
=== NAME  TestAccLogsLogGroup_logGroupClassDELIVERY2
    group_test.go:383: stopping VCR recorder
    group_test.go:383: persisting randomness seed
--- PASS: TestAccLogsLogGroup_logGroupClassDELIVERY2 (35.85s)
=== CONT  TestAccLogsLogGroup_Identity_RegionOverride
=== NAME  TestAccLogsLogGroup_multiple
    group_test.go:263: stopping VCR recorder
    group_test.go:263: persisting randomness seed
--- PASS: TestAccLogsLogGroup_multiple (36.18s)
=== NAME  TestAccLogsLogGroup_disappears
    group_test.go:124: stopping VCR recorder
    group_test.go:124: persisting randomness seed
--- PASS: TestAccLogsLogGroup_disappears (37.99s)
=== NAME  TestAccLogsLogGroup_namePrefix
    group_test.go:95: stopping VCR recorder
    group_test.go:95: persisting randomness seed
--- PASS: TestAccLogsLogGroup_namePrefix (43.46s)
=== NAME  TestAccLogsLogGroup_basic
    group_test.go:33: stopping VCR recorder
    group_test.go:33: persisting randomness seed
--- PASS: TestAccLogsLogGroup_basic (45.84s)
=== NAME  TestAccLogsLogGroup_nameGenerate
    group_test.go:67: stopping VCR recorder
    group_test.go:67: persisting randomness seed
--- PASS: TestAccLogsLogGroup_nameGenerate (45.87s)
=== NAME  TestAccLogsLogGroup_providerMeta
    group_test.go:810: stopping VCR recorder
    group_test.go:810: persisting randomness seed
--- PASS: TestAccLogsLogGroup_providerMeta (45.89s)
=== NAME  TestAccLogsLogGroup_skipDestroyInconsistentPlan
    group_test.go:310: stopping VCR recorder
    group_test.go:310: persisting randomness seed
--- PASS: TestAccLogsLogGroup_skipDestroyInconsistentPlan (52.92s)
=== NAME  TestAccLogsLogGroup_deletionProtectionEnabled
    group_test.go:777: stopping VCR recorder
    group_test.go:777: persisting randomness seed
--- PASS: TestAccLogsLogGroup_deletionProtectionEnabled (57.96s)
=== NAME  TestAccLogsLogGroup_tags_EmptyMap
    group_tags_gen_test.go:287: stopping VCR recorder
    group_tags_gen_test.go:287: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags_EmptyMap (63.81s)
=== NAME  TestAccLogsLogGroup_tags_null
    group_tags_gen_test.go:216: stopping VCR recorder
    group_tags_gen_test.go:216: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags_null (63.88s)
=== NAME  TestAccLogsLogGroup_Identity_Basic
    group_identity_gen_test.go:33: stopping VCR recorder
    group_identity_gen_test.go:33: persisting randomness seed
--- PASS: TestAccLogsLogGroup_Identity_Basic (65.16s)
=== NAME  TestAccLogsLogGroup_logGroupClassDELIVERY1
    group_test.go:342: stopping VCR recorder
    group_test.go:342: persisting randomness seed
--- PASS: TestAccLogsLogGroup_logGroupClassDELIVERY1 (66.83s)
=== NAME  TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Replace
    group_tags_gen_test.go:673: stopping VCR recorder
    group_tags_gen_test.go:673: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Replace (67.89s)
=== NAME  TestAccLogsLogGroup_tags_AddOnUpdate
    group_tags_gen_test.go:354: stopping VCR recorder
    group_tags_gen_test.go:354: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags_AddOnUpdate (68.02s)
=== NAME  TestAccLogsLogGroup_tags_EmptyTag_OnCreate
    group_tags_gen_test.go:439: stopping VCR recorder
    group_tags_gen_test.go:439: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags_EmptyTag_OnCreate (71.17s)
=== NAME  TestAccLogsLogGroup_kmsKey
    group_test.go:150: stopping VCR recorder
    group_test.go:150: persisting randomness seed
--- PASS: TestAccLogsLogGroup_kmsKey (72.74s)
=== NAME  TestAccLogsLogGroup_retentionPolicy
    group_test.go:219: stopping VCR recorder
    group_test.go:219: persisting randomness seed
--- PASS: TestAccLogsLogGroup_retentionPolicy (72.74s)
=== NAME  TestAccLogsLogGroup_Identity_RegionOverride
    group_identity_gen_test.go:120: stopping VCR recorder
    group_identity_gen_test.go:120: persisting randomness seed
--- PASS: TestAccLogsLogGroup_Identity_RegionOverride (39.07s)
=== NAME  TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Add
    group_tags_gen_test.go:532: stopping VCR recorder
    group_tags_gen_test.go:532: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags_EmptyTag_OnUpdate_Add (51.59s)
=== NAME  TestAccLogsLogGroup_tags
    group_tags_gen_test.go:30: stopping VCR recorder
    group_tags_gen_test.go:30: persisting randomness seed
--- PASS: TestAccLogsLogGroup_tags (63.06s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/logs       104.973s
```

Note: Failed replays are due to acceptance tests which are skipped when
`go-vcr` is enabled, but include references to wrapped helper functions
that expect a randomness source to exist on disk when in replay mode.
These particular cases will be resolved once support for per-test step
provider factories is enabled, which is being tracked in a separate
issue.