Acceptance test output (error is expected):
% make testacc TESTARGS='-run=TestAccS3BucketInventory_directoryBucket' PKG=s3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-aws_s3_bucket_inventory-directory-buckets 🌿...
TF_ACC=1 go1.26.2 test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3BucketInventory_directoryBucket -timeout 360m -vet=off
2026/04/21 08:35:35 Creating Terraform AWS Provider (SDKv2-style)...
2026/04/21 08:35:35 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccS3BucketInventory_directoryBucket
=== PAUSE TestAccS3BucketInventory_directoryBucket
=== CONT  TestAccS3BucketInventory_directoryBucket
    bucket_inventory_test.go:131: Step 1/1, expected an error but got none
--- FAIL: TestAccS3BucketInventory_directoryBucket (18.37s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/s3 24.132s
FAIL
make: *** [testacc] Error 1